In [1]:
import torch
from torch import nn

In [2]:
output = torch.rand(5)
output

tensor([0.8211, 0.5728, 0.4343, 0.5089, 0.1811])

In [3]:
target = torch.empty(5).random_(2)
target

tensor([1., 1., 0., 1., 1.])

In [4]:
loss = nn.BCELoss(reduction='none')
l1 = loss(output.sigmoid(), target)
l1

tensor([0.3646, 0.4472, 0.9337, 0.4707, 0.6067])

In [5]:
weight = target.shape[0] / target.sum(0)
weight

tensor(1.2500)

In [6]:
loss = nn.BCELoss(weight, reduction='none')

In [7]:
l2 = loss(output.sigmoid(), target)
l2

tensor([0.4558, 0.5590, 1.1671, 0.5884, 0.7583])

In [8]:
l2/l1

tensor([1.2500, 1.2500, 1.2500, 1.2500, 1.2500])

In [9]:
output = torch.rand((5,3))
output

tensor([[0.8827, 0.9224, 0.8198],
        [0.4837, 0.2575, 0.2761],
        [0.8587, 0.7867, 0.3106],
        [0.7399, 0.7101, 0.4892],
        [0.5154, 0.5870, 0.6310]])

In [10]:
target = torch.empty((5,3)).random_(2)
target

tensor([[0., 0., 0.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 1., 0.],
        [0., 0., 0.]])

In [11]:
loss = nn.BCELoss(reduction='none')

In [12]:
l1 = loss(output.sigmoid(), target)
l1

tensor([[1.2289, 1.2571, 1.1848],
        [0.4803, 0.5727, 0.5646],
        [1.2120, 1.1620, 0.8605],
        [1.1300, 0.3998, 0.9674],
        [0.9837, 1.0291, 1.0576]])

In [13]:
loss = nn.BCELoss(reduction='mean')

In [14]:
loss(output.sigmoid(), target)

tensor(0.9394)

In [15]:
l1.mean()

tensor(0.9394)

In [13]:
weight = (target.shape[0] / target.sum(0))
weight

tensor([2.5000, 1.6667, 1.6667])

In [14]:
loss = nn.BCELoss(weight, reduction='none')

In [15]:
l2 = loss(output.sigmoid(), target)
l2

tensor([[0.8096, 0.5542, 0.9968],
        [2.3110, 1.3651, 0.6730],
        [2.1915, 1.7890, 0.5930],
        [1.6745, 0.5873, 1.7721],
        [2.5173, 0.7013, 1.3532]])

In [16]:
l2/l1

tensor([[2.5000, 1.6667, 1.6667],
        [2.5000, 1.6667, 1.6667],
        [2.5000, 1.6667, 1.6667],
        [2.5000, 1.6667, 1.6667],
        [2.5000, 1.6667, 1.6667]])

In [ ]:
output = torch.rand(5)
output

In [17]:
target = torch.empty(5).random_(2)
target

tensor([1., 1., 1., 0., 0.])

In [18]:
loss = nn.BCEWithLogitsLoss(reduction='none')
l1 = loss(output, target)
l1

ValueError: Target size (torch.Size([5])) must be the same as input size (torch.Size([5, 3]))

In [ ]:
weight = target.shape[0] / target.sum(0) -1
weight

In [ ]:
loss = nn.BCEWithLogitsLoss(pos_weight=weight, reduction='none')

In [ ]:
l2 = loss(output.sigmoid(), target)
l2

In [ ]:
l2/l1

In [ ]:
output = torch.rand((5,3))
output

In [ ]:
target = torch.empty((5,3)).random_(2)
target

In [ ]:
weight = target.shape[0]/target.sum(0)-1
weight

In [ ]:
loss = nn.BCEWithLogitsLoss(reduction='none')

In [ ]:
l1 = loss(output, target)
l1

In [ ]:
loss = nn.BCEWithLogitsLoss(pos_weight=weight, reduction='none')

In [ ]:
l2 = loss(output, target)
l2

In [ ]:
l2/l1