In [1]:
import torch
from torch import nn

In [2]:
output = torch.rand(5)
output

tensor([0.1794, 0.3517, 0.9067, 0.5154, 0.4298])

In [3]:
target = torch.empty(5).random_(2)
target

tensor([1., 0., 1., 0., 1.])

In [4]:
loss = nn.BCELoss(reduction='none')
l1 = loss(output.sigmoid(), target)
l1

tensor([0.6075, 0.8844, 0.3392, 0.9837, 0.5012])

In [5]:
weight = target.shape[0] / target.sum(0)
weight

tensor(1.6667)

In [6]:
loss = nn.BCELoss(weight, reduction='none')

In [7]:
l2 = loss(output.sigmoid(), target)
l2

tensor([1.0124, 1.4739, 0.5654, 1.6395, 0.8353])

In [8]:
l2/l1

tensor([1.6667, 1.6667, 1.6667, 1.6667, 1.6667])

In [9]:
output = torch.rand((5,3))
output

tensor([[0.3607, 0.0042, 0.4049],
        [0.2757, 0.8330, 0.4210],
        [0.4518, 0.9639, 0.5282],
        [0.7350, 0.5255, 0.0768],
        [0.2860, 0.5654, 0.8465]])

In [10]:
target = torch.empty((5,3)).random_(2)
target

tensor([[0., 0., 0.],
        [1., 0., 1.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 1., 1.]])

In [11]:
loss = nn.BCELoss(reduction='none')

In [12]:
l1 = loss(output.sigmoid(), target)
l1

tensor([[0.8897, 0.6953, 0.9160],
        [0.5648, 1.1940, 0.5047],
        [0.4925, 1.2870, 0.9917],
        [0.3917, 0.9900, 0.7323],
        [0.5603, 0.4499, 0.3569]])

In [23]:
weight = (target.shape[0] / target.sum(0))
weight

tensor([1.2500, 5.0000, 2.5000])

In [24]:
loss = nn.BCELoss(weight, reduction='none')

In [25]:
l2 = loss(output.sigmoid(), target)
l2

tensor([[1.1121, 3.4763, 2.2899],
        [0.7060, 5.9700, 1.2616],
        [0.6157, 6.4349, 2.4793],
        [0.4896, 4.9500, 1.8307],
        [0.7004, 2.2495, 0.8922]])

In [26]:
l2/l1

tensor([[1.2500, 5.0000, 2.5000],
        [1.2500, 5.0000, 2.5000],
        [1.2500, 5.0000, 2.5000],
        [1.2500, 5.0000, 2.5000],
        [1.2500, 5.0000, 2.5000]])

In [32]:
output = torch.rand(5)
output

tensor([0.7790, 0.6226, 0.9015, 0.9376, 0.3137])

In [33]:
target = torch.empty(5).random_(2)
target

tensor([0., 1., 0., 0., 0.])

In [34]:
loss = nn.BCEWithLogitsLoss(reduction='none')
l1 = loss(output, target)
l1

tensor([1.1567, 0.4295, 1.2422, 1.2680, 0.8622])

In [39]:
weight = target.shape[0] / target.sum(0) -1
weight

tensor(4.)

In [40]:
loss = nn.BCEWithLogitsLoss(pos_weight=weight, reduction='none')

In [41]:
l2 = loss(output.sigmoid(), target)
l2

tensor([1.0935, 1.6791, 1.1107, 1.1157, 1.0232])

In [42]:
l2/l1

tensor([0.9454, 3.9092, 0.8941, 0.8799, 1.1867])

In [45]:
output = torch.rand((5,3))
output

tensor([[0.6513, 0.5143, 0.1396],
        [0.8284, 0.9745, 0.4745],
        [0.5401, 0.4382, 0.8424],
        [0.4669, 0.3595, 0.5383],
        [0.9766, 0.0516, 0.7020]])

In [46]:
target = torch.empty((5,3)).random_(2)
target

tensor([[1., 0., 1.],
        [0., 0., 0.],
        [1., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.]])

In [48]:
weight = target.shape[0]/target.sum(0)-1
weight

tensor([0.6667, 4.0000, 1.5000])

In [49]:
loss = nn.BCEWithLogitsLoss(reduction='none')

In [50]:
l1 = loss(output, target)
l1

tensor([[0.4196, 0.9830, 0.6258],
        [1.1908, 1.2947, 0.9583],
        [0.4591, 0.9361, 1.2005],
        [0.9536, 0.8890, 0.9981],
        [0.3196, 0.6677, 0.4025]])

In [51]:
loss = nn.BCEWithLogitsLoss(pos_weight=weight, reduction='none')

In [52]:
l2 = loss(output, target)
l2

tensor([[0.2797, 0.9830, 0.9386],
        [1.1908, 1.2947, 0.9583],
        [0.3061, 0.9361, 1.2005],
        [0.9536, 0.8890, 0.9981],
        [0.2131, 2.6707, 0.6038]])

In [53]:
l2/l1

tensor([[0.6667, 1.0000, 1.5000],
        [1.0000, 1.0000, 1.0000],
        [0.6667, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000],
        [0.6667, 4.0000, 1.5000]])